name: FUNCTION CI

on:
  pull_request:
    branches: [ main ]

jobs:
  sec:
    runs-on: ubuntu-latest
    permissions: write-all
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_ENABLE_UPLOAD_ARTIFACT: 'false'
        GITLEAKS_VERSION: '8.28.0'
        GITLEAKS_LOG_LEVEL: 'trace'
  
  test-build:
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: ./function
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./function/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run linter
      run: npm run lint
    
    - name: Build
      run: npm run build
